# Generated by Django 5.2 on 2025-07-06 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_cafe', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidocafe',
            name='precio',
        ),
        migrations.AddField(
            model_name='pedidocafe',
            name='cliente',
            field=models.CharField(blank=True, help_text='Nombre del cliente', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedidocafe',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, help_text='Fecha y hora del pedido', null=True),
        ),
        migrations.AlterField(
            model_name='pedidocafe',
            name='ingredientes',
            field=models.JSONField(blank=True, default=list, help_text='Lista de ingredientes', null=True),
        ),
    ]
