# Generated by Django 5.2 on 2025-07-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_cafe', '0003_alter_pedidocafe_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidocafe',
            name='ingredientes',
            field=models.JSONField(blank=True, default=list, help_text='leche, azúcar, canela, chocolate, vainilla, caramelo, miel', null=True),
        ),
    ]
